# Generated by Django 3.1.5 on 2021-01-26 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebCLI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithm',
            old_name='user_id',
            new_name='user',
        ),
    ]
