# Generated by Django 3.1.5 on 2021-01-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebCLI', '0002_auto_20210126_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
