# Generated by Django 3.1.5 on 2021-02-01 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebCLI', '0003_auto_20210126_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Algorithm',
        ),
        migrations.DeleteModel(
            name='Algorithm_type',
        ),
        migrations.DeleteModel(
            name='Molecule',
        ),
    ]
