# Generated by Django 3.1.5 on 2021-02-01 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebCLI', '0004_auto_20210201_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('structure', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('public', models.BooleanField()),
                ('algorithm', models.TextField()),
                ('iterations', models.IntegerField(null=True)),
                ('measurements', models.IntegerField(null=True)),
                ('circuit_depth', models.IntegerField(null=True)),
                ('accuracy', models.FloatField(null=True)),
                ('algorithm_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebCLI.algorithm_type')),
                ('molecule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebCLI.molecule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
